# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


trigger:
  branches:
    include:
      - main
      
pool:
  vmImage: ubuntu-latest

  steps:
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: './'
      displayName: "installing dependencies"
    - task: Npm@1
      inputs:
        command: 'run build'
        workingDir: './'
  displayName: "building project"

step:
   - task: Docker@2
     inputs:
      containerRegistry: 'docker-registry'
      repository: '.'
      command: 'buildAndPush'
     Dockerfile: '**/Dockerfile'
