apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbinclui-app-${ENV}
  namespace: dbinclui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbinclui-app-${ENV}
  template:
    metadata:
      labels:
        app: dbinclui-app-${ENV}
    spec:
      containers:
        - name: dbinclui-app-${ENV}
          image: "dbserverregistry.azurecr.io/dbinclui/frontend"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
           envFrom:
            - configMapRef:
                name: dbinclui-app-configmap-${env}
