apiVersion: v1
items:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: dbinclui-${ENV}
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
    spec:
      rules:
        - host: ${INGRESS_DOMAIN}.paas.dbserver.com.br
          http:
            paths:
              - pathType: Prefix
                path: /
                backend:
                  service:
                    name: dbinclui-app-service-${ENV}
                    port:
                      number: 80
        - host: ${INGRESS_DOMAIN}-api.paas.dbserver.com.br
          http:
            paths:
            - pathType: Prefix
              path: /
              backend:
                service:
                  name: dbinclui-api-service-${ENV}
                  port:
                    number: 80
      tls:
        - hosts:
            - ${INGRESS_DOMAIN}.paas.dbserver.com.br
            - ${INGRESS_DOMAIN}-api.paas.dbserver.com.br
          secretName: dbinclui-${ENV}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
